version: '3.8'
services:
  springboot-r2dbc-crud-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: r2dbc
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  springboot-r2dbc-crud-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: r2dbc:mysql://springboot-r2dbc-crud-db:3306/r2dbc
    ports:
      - 9898:9899
    depends_on:
      - springboot-r2dbc-crud-db
    restart: always

volumes:
  db_data: {}
