spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/r2dbc
    username: username
    password: password
  data:
    r2dbc:
      repositories:
        enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 9899

logging:
  level:
    io.r2dbc.spi: DEBUG
    org.springframework.r2dbc: DEBUG
